FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install python3 python3-pip

ADD pip.docker.sh /
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN apt-get -y install libzbar0

RUN ./pip.docker.sh

